### ISSUE TITLE
Incorporate TimesFM into MAJ 

### ISSUE THREAD

**Issue by stuagano** [GoogleCloudPlatform/marketing-analytics-jumpstart#112]
https://github.com/google-research/timesfm. Context. This was just announced at next but for forecasting and prediction use cases this would be amazing.

**Comment by chmstimoteo** [comment]
This is out of the scope. This assume a time-series forecasting use case, which is not relevant to the use cases we implement. Our use cases are regression and classification, not time-series forecasting use cases.

**Comment by chmstimoteo** [comment]
This won't be implemented as it is not applicable,

**Comment by chmstimoteo** [comment]
I've added all the modelling principles for the models here: [docs/ml_specs.md](https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/docs/ml_specs.md)

It also explains why TimesFM is not applicable to us.
