### ISSUE TITLE
pipelines get automatically scheduled but dont contain any parameters. 

### ISSUE THREAD

**Issue by stuagano** [GoogleCloudPlatform/marketing-analytics-jumpstart#113]
<img width="1456" alt="image" src="https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/assets/8115246/171c9ad3-e247-463b-ba8d-2a35afb1216f">

I am currently redeploying feature creation pipelines to better use the parameters that they should be. The terraform deployment doesnt include this.

**Comment by stuagano** [comment]
note how the names are different on the scheduled runs i have manually created v the scheduled pipelines

**Comment by chmstimoteo** [comment]
The Vertex AI pipelines schedules API now works with the name definition. This issue is fixed.
