### ISSUE TITLE
Cloud Source Repositories issue

### ISSUE THREAD

**Issue by pulporange** [GoogleCloudPlatform/marketing-analytics-jumpstart#160]
When applying the Terraform configuration to the project an error arise saying that it's not possible to enable the Cloud Source Repositories API

Which seems to relate to the following change, during our initial conversation it seems that this API is no longer needed, so it should be a quick fix.

_Effective June 17, 2024, Cloud Source Repositories isn't available to new customers. If your organization hasn't previously used Cloud Source Repositories, you can't enable the API or use Cloud Source Repositories. New projects not connected to an organization can't enable the Cloud Source Repositories API. Organizations that have used Cloud Source Repositories prior to June 17, 2024 are not affected by this change._

**Comment by chmstimoteo** [comment]
Fixed in PR: https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/pull/159
