### ISSUE TITLE
Marketing Analytics Jumpstart's Dashboard doesn't work Due to Missing projectId Error in Looker Studio

### ISSUE THREAD

**Issue by CairoAC** [GoogleCloudPlatform/marketing-analytics-jumpstart#161]
I attempted to install the Marketing Analytics Jumpstart project following the step-by-step guide using "Open in Cloud Shell". However, I face this error when trying to access the Looker Studio report:

Something went wrong while creating your report
A value is missing for ds.Activation_log.projectId

Steps to Reproduce

Follow the step-by-step installation guide using "Open in Cloud Shell".

Expected Behavior

The Looker Studio report should be working successfully.

Actual Behavior

The report shows an error message indicating a missing projectId for ds.Activation_log.

**Comment by chmstimoteo** [comment]
Hi @CairoAC , please check if now the Looker Dashboard is going to work. We've just merged a fix for it https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/pull/176

**Comment by CairoAC** [comment]
@chmstimoteo honestly what worked for me was to check for dataform execution logs. It wasn't working so the prod dataset was empty. I don't know why Looker showed that error message though
