### ISSUE TITLE
Possibly redundant procedure?

### ISSUE THREAD

**Issue by MatteoEgmont** [GoogleCloudPlatform/marketing-analytics-jumpstart#168]
Hi and thanks for maintaining this package!
I was looking at [invoke_purchase_propensity_training_preparation](https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/blob/main/sql/query/invoke_purchase_propensity_training_preparation.sqlx) and noticed that the final part of the procedure seems now redundant?

[These lines](https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/blob/d0c4381a4c9531ff69f67e167c0459f465405bbf/sql/query/invoke_purchase_propensity_training_preparation.sqlx#L45-L47)

````
-- Initializing Training Dates
SET train_start_date = min_date;
SET train_end_date = max_date;
````

means that [these other lines](https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/blob/d0c4381a4c9531ff69f67e167c0459f465405bbf/sql/query/invoke_purchase_propensity_training_preparation.sqlx#L62-L68)

````
IF purchasers > 0 THEN
    SET train_start_date =  GREATEST(train_start_date, min_date);
    SET train_end_date = LEAST(train_end_date, max_date);
ELSE
    SET train_start_date =  min_date;
    SET train_end_date = max_date;
END IF;
````

will always produce the same result regardless the value of `purchasers`, since `train_start_date=min_date` and `train_end_date=max_date` ?

Thanks for double checking 😄 
/Matteo

**Comment by chmstimoteo** [comment]
Thanks @MatteoEgmont , I'm removing these lines.

```
-- Initializing Training Dates
SET train_start_date = min_date;
SET train_end_date = max_date;
```
