### ISSUE TITLE
hardcoded region?

### ISSUE THREAD

**Issue by MatteoEgmont** [GoogleCloudPlatform/marketing-analytics-jumpstart#169]
Hi, when deploying with terraform, I am getting this error message
````
Not found: Dataset gemini_insights was not found in location US
````
which is likely due to this [hardcoded reference](https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/blob/d0c4381a4c9531ff69f67e167c0459f465405bbf/sql/query/create_gemini_model.sqlx#L18) (clashing with the rest of the deployment being EU-multiregion)

Thanks for your help
/Matteo

**Comment by chmstimoteo** [comment]
Hi @MatteoEgmont , nice catch, I'm going to use the same region as defined for the dataset.

Thanks!
