### ISSUE TITLE
Content of purchase_propensity_label and effect on purchase_propensity_training_full_dataset

### ISSUE THREAD

**Issue by MatteoEgmont** [GoogleCloudPlatform/marketing-analytics-jumpstart#173]
Hi! I was wondering how `purchase_propensity_label` is created and what it is meant to contain. This might possibly relate to https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/issues/165, and if so apologies for duplicating it 😄 

In the two temporary tables we create, the `event` base table is filtered out:
- first with [this where clause](https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/blob/3cbe170e62d51ffc11d048a5189e8d0f0d562e76/sql/procedure/purchase_propensity_label.sqlx#L63) for creating `future_purchases_per_user`
- then  with [this other where clause](https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/blob/3cbe170e62d51ffc11d048a5189e8d0f0d562e76/sql/procedure/purchase_propensity_label.sqlx#L100) for creating `all_users_possible_purchases`.

The result should then be that any `user_pseudo_id`'s with no `purchase` events will not be present in the table containing labels.

When creating the table `purchase_propensity_training_full_dataset` we then use an [inner join](https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/blob/3cbe170e62d51ffc11d048a5189e8d0f0d562e76/sql/procedure/purchase_propensity_training_preparation.sqlx#L346) for joining `purchase_propensity_label` to the various user dimensions and metrics. This should also mean that any `user_pseudo_id`'s with no `purchase` events will be missing from `purchase_propensity_training_full_dataset`.

Since `purchase_propensity_training_full_dataset` is the dataset used for creating the various tables and views ultimately used for training the classifier in Vertex, aren't we excluding from the training dataset for "propensity to purchase" the majority of users who never purchased and training the model only on a reduced subset? Worst case that could event result in a "class 0" which is completely missing from the training data (hence why I thought it could be related to https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/issues/165)

Wouldn't be better to either have `purchase_propensity_label` containing all visitors' labels, or perhaps left joining labels and then coalesce'ing when creating `purchase_propensity_training_full_dataset`? 

Thanks!
/Matteo

**Comment by chmstimoteo** [comment]
Hi @MatteoEgmont , thanks for catching that up.
After some thought and analysis, we have applied the following PR: https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/pull/175
