### ISSUE TITLE
Local exec provisioner error - Vertex AI builds pipeline in wrong location due to default settings

### ISSUE THREAD

**Issue by jakubpietrzyk21** [GoogleCloudPlatform/marketing-analytics-jumpstart#215]
Hi,
During implementation of marketing analytics jumpstart at the last phase of installation of terraform modules on command "terraform -chdir="${TERRAFORM_RUN_DIR}" apply" I got an error (attachment).
After consultation it means that Vertex AI due to default settings try to build pipeline in location "us" but in our company we have location restrictions only to Europe regions or multi-region.
I would like to ask to help me with this issue and change it to work properly in our personal scenario.

Best regards

![error Vertex AI pipeline 2](https://github.com/user-attachments/assets/e521e2eb-0c76-42d6-9917-169a08b6cfd9)
![error Vertex AI pipeline](https://github.com/user-attachments/assets/53ed0346-41ff-453f-b78f-b5c2d210558c)

**Comment by chmstimoteo** [comment]
Hi @jakubpietrzyk21 , curiously, I was working on this fix with another colleague this morning.
I have a found the issue root-cause and made the fix.
https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/commit/b4d0fa7ccda2d9fbc02e509deb6f9a57b67403ac

You should have that resolved, could you please run `terraform .. apply` again?

Carlos.
