### ISSUE TITLE
Pipelines are being created in US Central 1 regardless of region specificed 

### ISSUE THREAD

**Issue by DaveWard-looker** [GoogleCloudPlatform/marketing-analytics-jumpstart#216]
I have set region to southamerica-east1 throughout the MAJ however all pipelines are created within US-Central1 regardless. 

![image](https://github.com/user-attachments/assets/c7f7dc34-d5d9-49fb-9c64-28bef8f10e2e)

**Comment by chmstimoteo** [comment]
Thanks @DaveWard-looker , solved with a quick workaround and finally implemented with this PR: https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/pull/219
