### ISSUE TITLE
Local exec provisioner error - activation pipeline - violation resource location

### ISSUE THREAD

**Issue by jakubpietrzyk21** [GoogleCloudPlatform/marketing-analytics-jumpstart#221]
Hi again,
I have already posted one issue connected to local exec provisioner error
https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/issues/215

After patches it all went very well (good job guys!) but once again the error occured.
![image](https://github.com/user-attachments/assets/74a33bf8-ea87-4185-b0a5-7db41a98f5bb)

**Comment by kingman** [comment]
@jakubpietrzyk21 we added this change last week:
https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/blob/main/infrastructure/terraform/modules/activation/main.tf#L828 which ensures that the build is kept in the specific region for the build, could you re-try this in your environment and validate whether the change fixes the issue? You may also need to delete the existing cloud build bucket `{project_id}_cloudbuild` if its created in the wrong region.

**Comment by jakubpietrzyk21** [comment]
Hey,
Thanks for your comment!
For sure I will re-try but first I want have comments to all of my issues -> #228

**Comment by chmstimoteo** [comment]
Issue solved!
