### ISSUE TITLE
Segmentation model training preparation failing to pull feature data due to outdated defaults

### ISSUE THREAD

**Issue by danchapman** [GoogleCloudPlatform/marketing-analytics-jumpstart#34]
For the segmentation training preparation, the end of the date range for the training window is defaulting to a config value that is quite old, and therefore not picking up any rows for training. In addition, given that the training window is rolling forward in time, using a hard config value as a default for a training window is not sustainable otherwise weekly training would require config changes and terraform builds when the window date could easily be based off of the current date. 

The training end date is currently hard coded here:
https://github.com/GoogleCloudPlatform/marketing-data-engine/blob/37c5635af74c2ffe7794496a7244a947d8440a55/config/config.yaml.tftpl#L596

In this line, given today's date, it will always be the LEAST value, and so will always be set to `2023-03-12` which causes the query getting the range of values to train on to return no rows:
https://github.com/GoogleCloudPlatform/marketing-data-engine/blob/37c5635af74c2ffe7794496a7244a947d8440a55/sql/query/invoke_audience_segmentation_training_preparation.sqlx#L33C3-L33C3

What's more, even if the GREATEST value was selected, the query would still be off because this line is choosing a value 15 days in the past, which doesn't make sense. I would expect that the max value would be based on the last day in which GA data is present:
https://github.com/GoogleCloudPlatform/marketing-data-engine/blob/37c5635af74c2ffe7794496a7244a947d8440a55/sql/query/invoke_audience_segmentation_training_preparation.sqlx#L22

running from the last data that has GA data available minus the number look back interval days. This range doesn't seem like what we want to train on. It seems like we would want the backfill end date on the day before the current date.

**As of now, given these parameters:**
GA data available in the marketing data store : 7/19/23 - 8/9/23
Interval Min Date : 15
The training SQL uses an end date of : 3/12/23
No training happens. 

**What I would expect:**
GA data available in the marketing data store : 7/19/23 - 8/9/23
Interval Min Date : 15
The training SQL uses an end date of : 8/9/23
Training happens on data from : 7/25/23 - 8/8/23

I might be missing some nuance here, but I can confirm that the above scenario today is failing to train a model due to no rows being available.

**Comment by chmstimoteo** [comment]
Fixed this issue by assuming default values from data existing on events fact table.
