### ISSUE TITLE
Enable users to temporarily pause MAJ in their GCP project

### ISSUE THREAD

**Issue by mansiparikh** [GoogleCloudPlatform/marketing-analytics-jumpstart#66]
Received the following Google support in chat on how to pause MAJ in their GCP project to stop incurring processing and storage costs of generated tables. Please add this feature to the repo.

How to do it:
Search for workflows in the search to quickly get to workflows console page. In workflow you will see the daily incremental dataform job. If you delete workflow, it will not continue daily data collection from the BigQuery export tables. 
To pause the vertex pipelines you can go to http://console.cloud.google.com/vertex-ai/pipelines/schedules and and pause all the scheduled jobs. 

How to check: 
Go to http://console.cloud.google.com/bigquery/dataform/locations/us-central1/repositories/marketing-analytics/details/workflows and check when the execution was last run. If it turned off, you will not get new execution in this list.
Check all the vertex-ai pipeline schedules are paused as well

**Comment by chmstimoteo** [comment]
@mansiparikh why would you stop the processing of the data and sending the predictions to your Google Ads property?

**Comment by mansiparikh** [comment]
> @mansiparikh why would you stop the processing of the data and sending the predictions to your Google Ads property?

Hello, Carlos! Thanks for the reply. It's for when clients need to pause between the implementation and the next project since the most use of jumpstart can come when there is follow-on work of some kind but the data cannot be collected in the meantime (storage bill, etc.).

**Comment by chmstimoteo** [comment]
This issue is fixed in the documentation. In the `config.yaml.tftpl` the pipelines are PAUSED by default. Making one paying attention to ENABLING them before use.
