### ISSUE TITLE
Error, deleting bucket requires force_destroy

### ISSUE THREAD

**Issue by patsmarketinganalyticsdemo** [GoogleCloudPlatform/marketing-analytics-jumpstart#71]
When running the terraform apply, I get this error:

│ Error: Error trying to delete bucket [project]-pipelines containing objects without `force_destroy` set to true

Replace [project] with the project id. 

This is the terraform apply command used: 

```
terraform \
    -chdir="${TERRAFORM_RUN_DIR}" \
    apply
 ```

I'd expect for the apply command to finish successfully.

**Comment by patsmarketinganalyticsdemo** [comment]
If I delete the pipelines bucket manually, then I'm able to re-run apply and proceed.

**Comment by chmstimoteo** [comment]
This is a protection to make sure we don't loose important lineage metadata stored in the pipelines bucket.
This is the correct expected behaviour.
