### ISSUE TITLE
Enhancement: Consider impact activation app has on GA UX

### ISSUE THREAD

**Issue by iampatgrady** [GoogleCloudPlatform/marketing-analytics-jumpstart#79]
Hello, 

We have concerns about the number of events being sent to GA4 with the same timestamp. Initial investigation showed that events are transmitted frequently for a single client_id for activity over a 15-day lookback period; however, the event timestamp is current. 

It would be better to reduce the lookback window, for example to 3 days, as well as change the event timestamp to be the last session timestamp; finally, only send the hit if the prediction has changed, and perhaps changed beyond a configurable threshold.

**Comment by kingman** [comment]
Hi @iampatgrady, whith this [PR](https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/pull/77) the first two requirements now in place for activation:
* lookback window 72 hours (which is the limit for Measurement Protocol)
* The timestamp is now set to 1 microsecond after the last event timestamp
In order for this to work you will also need pull the latest change into the Dataform repository, as part of the change is in Dataform.

The last requirements we'll need to discuss within the team on how to best fulfill.

Thanks you!
