### ISSUE TITLE
Failed to create pipeline error when deploying runs of KFP Pipelines 

### ISSUE THREAD

**Issue by stuagano** [GoogleCloudPlatform/marketing-analytics-jumpstart#82]
Failed to create pipeline job. Error: The image us-west1-docker.pkg.dev/white-gate-363817/pipelines-docker-repo/ma-components:dev does not exist..

I have the Artifact registry set up and everything as a kfp repo and the string name is the same. I dont see a "ma-components:dev" artifact in the repo. Not sure what needs to be changed? 

This URI is different than my template URI which is https://us-west1-kfp.pkg.dev/white-gate-363817/pipelines-repo/feature-creation-audience-segmentation/sha256:05c85f221e9120425bcee0763d45f2a5b402ecaedff5d3e7043d10ecedb29

So not sure where to go from here.

**Comment by chmstimoteo** [comment]
The `ma-components:dev` is the name of the component docker image. if this docker image is not being created, it will silently fail during the terraform deployment. The image will be uploaded to Artifact Registry in a Docker Image Repository.

> This URI is different than my template URI which is https://us-west1-kfp.pkg.dev/white-gate-363817/pipelines-repo/feature-creation-audience-segmentation/sha256:05c85f221e9120425bcee0763d45f2a5b402ecaedff5d3e7043d10ecedb29

This URI has nothing to do with the docker image cited before. This `feature-creation-audience-segmentation` pipeline is stored in Artifact Registry in a Kubeflow Pipeline Repository.

**Comment by chmstimoteo** [comment]
@stuagano please run `terraform .. apply` with the following target and share a screenshot of the logs found in the Terminal.

`terraform -chdir="${TERRAFORM_RUN_DIR}" apply -target=module.pipelines[0].null_resource.build_push_pipelines_components_image`

**Comment by chmstimoteo** [comment]
stale... not able to reproduce.

**Comment by martenlindblad** [comment]
We ran the terraform apply using europe-west3 as our region. This makes the build fail silently since we cannot use cloud build in that region. Terraform marks the image as created but that's not the case.
