### ISSUE TITLE
manual changes required after running terraform apply

### ISSUE THREAD

**Issue by stuagano** [GoogleCloudPlatform/marketing-analytics-jumpstart#84]
hey after I run terraform apply it writes in place over my cloud workflow code that I need to then modify and fix.  This has to do with the google_ads table in dataform.json. The formatting for it needs to be _12345560 where this is the string for the ads customer id instead of _123-123-123

**Comment by stuagano** [comment]
Once i make this change the pipeline is able to be ran successfully.

**Comment by chmstimoteo** [comment]
@kingman could you have a look at this, pls?

**Comment by chmstimoteo** [comment]
What is the configuration value you have for `dataform_github_repo` in your `terraform.tfvars` file?

**Comment by chmstimoteo** [comment]
This issue could not been reproduced.

**Comment by stahn** [comment]
additional clarification in the docs/tutorial might be useful to state that Google Ads customer id should be without "-" just numbers
