### ISSUE TITLE
Git Provider disconnects after running terraform apply.

### ISSUE THREAD

**Issue by stuagano** [GoogleCloudPlatform/marketing-analytics-jumpstart#85]
Im sure this is something that I am doing wrong but after running terraform apply my project github dataform connection always breaks. Once I manually reconnect via my secret stored in Secret Manager things run fine again. I am sure its a thing with variables but not sure where to make this change. 

Thanks for any pointers

**Comment by chmstimoteo** [comment]
Is this issue found when working with Cloud Shell?
